[versions]

# Plugins
agp = "8.13.2"
kotlin = "2.0.20"
ksp = "2.0.20-1.0.24"

# AndroidX
activity = "1.9.3"
appcompat = "1.7.0"
core-ktx = "1.13.1"
constraint-layout = "2.1.4"
datastore-preferences = "1.1.1"

# Material
material = "1.12.0"

# Room
room = "2.6.1"

# Testing
espresso-core = "3.6.1"
androidx-junit = "1.2.1"
junit = "4.13.2"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }


[libraries]

# AndroidX
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraint-layout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }

# Material
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Testing
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }


[bundles]
androidx = [
    "androidx-activity",
    "androidx-appcompat",
    "androidx-constraintlayout",
    "androidx-core-ktx",
    "androidx-datastore-preferences"
]
